#!/bin/bash
# Weekly Planning Generator
# Usage: weekly-planning.sh [--dry-run]

set -euo pipefail

source "${OPENCLAW_CONFIG_SH:-/home/openclaw/.openclaw/config.sh}" 2>/dev/null || {
    OPENCLAW_VAULT="${OPENCLAW_VAULT:-/home/openclaw/obsidian-vault}"
    OPENCLAW_LOGS="${OPENCLAW_LOGS:-$OPENCLAW_VAULT/_System/Logs}"
    OPENCLAW_EXTRACTED="${OPENCLAW_EXTRACTED:-$OPENCLAW_VAULT/_System/Extracted}"
    OPENCLAW_SKILLS="${OPENCLAW_SKILLS:-/home/openclaw/.openclaw/skills}"
}

VAULT="$OPENCLAW_VAULT"
OUTPUT_DIR="$VAULT/01_Projects/Weekly-Plans"
WEEK_NUM=$(date +%V)
YEAR=$(date +%Y)
PLAN_FILE="$OUTPUT_DIR/${YEAR}-W${WEEK_NUM}-Plan.md"
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run) DRY_RUN=true; shift ;;
        *) shift ;;
    esac
done

mkdir -p "$OUTPUT_DIR"

log_action() {
    if [[ -x "$OPENCLAW_SKILLS/memory/log-action.sh" ]]; then
        "$OPENCLAW_SKILLS/memory/log-action.sh" "$1" "weekly-planning" "$2" "high"
    fi
}

categorize_priority() {
    local task="$1"
    if echo "$task" | grep -qiE "(urgent|asap|critical|deadline|today|tomorrow|!!!)"; then
        echo "high"
    elif echo "$task" | grep -qiE "(important|soon|this week|should|need to)"; then
        echo "medium"
    else
        echo "low"
    fi
}

generate_plan() {
    local today=$(date +%Y-%m-%d)
    cat << HEADER
---
created: $(date -Iseconds)
type: weekly-plan
week: $WEEK_NUM
year: $YEAR
status: active
---

# Weekly Plan: $YEAR-W$WEEK_NUM

**Generated**: $(date "+%A, %B %d, %Y at %H:%M")

## High Priority Tasks

HEADER

    local high_count=0
    while IFS= read -r -d '' file; do
        [[ "$file" =~ _System|\.trash|\.obsidian ]] && continue
        while IFS= read -r line; do
            if [[ "$line" =~ ^[[:space:]]*-[[:space:]]\[[[:space:]]\] ]]; then
                task=$(echo "$line" | sed 's/^[[:space:]]*-[[:space:]]\[[[:space:]]\][[:space:]]*//')
                priority=$(categorize_priority "$task")
                if [[ "$priority" == "high" ]]; then
                    if [[ $high_count -eq 0 ]]; then
                        echo "| # | Task |"
                        echo "|---|------|"
                    fi
                    ((high_count++))
                    echo "| $high_count | $task |"
                fi
            fi
        done < "$file"
    done < <(find "$VAULT" -name "*.md" -type f ! -path "*/_System/*" ! -path "*/.trash/*" -print0 2>/dev/null)

    [[ $high_count -eq 0 ]] && echo "*No high priority tasks identified.*"

    cat << FOOTER

---

## Weekly Schedule

| Day | Focus |
|-----|-------|
| Mon | Review priorities |
| Tue | Deep work |
| Wed | Mid-week check |
| Thu | Continue work |
| Fri | Wrap-up |

---

*Generated by OpenClaw Weekly Planning*
FOOTER
}

main() {
    echo "Generating weekly plan for $YEAR-W$WEEK_NUM..."
    if [[ "$DRY_RUN" == "true" ]]; then
        generate_plan
    else
        generate_plan > "$PLAN_FILE"
        log_action "weekly_plan_generated" "Created weekly plan for $YEAR-W$WEEK_NUM"
        echo "Weekly plan created: $PLAN_FILE"
    fi
}

main "$@"
